tmp

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -27,172 +27,173 @@ jobs:
       - name: Run unit tests 1
         run: |
           echo Running unit tests 1...
-          sleep 5
+          # sleep 5
+          echo ${{ github.event }}
 
-  integration-tests:
-    name: Run integration tests
-    runs-on: ubuntu-latest
-    needs: [unit-tests]
+  # integration-tests:
+  #   name: Run integration tests
+  #   runs-on: ubuntu-latest
+  #   needs: [unit-tests]
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v5
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v5
 
-      - name: Run integration tests
-        run: python test_integration.py
-        env:
-          SNOW_URL: https://dev280175.service-now.com
-          SNOW_STANDARD_CHANGE: 92b653b2537a7610065e78e0a0490e5e
-          SNOW_USER: ${{ secrets.SNOW_USER }}
-          SNOW_PASSWORD: ${{ secrets.SNOW_PASSWORD }}
+  #     - name: Run integration tests
+  #       run: python test_integration.py
+  #       env:
+  #         SNOW_URL: https://dev280175.service-now.com
+  #         SNOW_STANDARD_CHANGE: 92b653b2537a7610065e78e0a0490e5e
+  #         SNOW_USER: ${{ secrets.SNOW_USER }}
+  #         SNOW_PASSWORD: ${{ secrets.SNOW_PASSWORD }}
 
-  create-snow-change:
-    name: Create ServiceNow change
-    runs-on: ubuntu-latest
-    needs: [integration-tests]
-    permissions:
-      contents: write
-    env:
-      SNOW_URL: https://dev280175.service-now.com
-    outputs:
-      CHANGE_SYS_ID: ${{ steps.create-change.outputs.CHANGE_SYS_ID }}
+  # create-snow-change:
+  #   name: Create ServiceNow change
+  #   runs-on: ubuntu-latest
+  #   needs: [integration-tests]
+  #   permissions:
+  #     contents: write
+  #   env:
+  #     SNOW_URL: https://dev280175.service-now.com
+  #   outputs:
+  #     CHANGE_SYS_ID: ${{ steps.create-change.outputs.CHANGE_SYS_ID }}
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v5
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v5
 
-      - name: Bump version and push tag
-        uses: anothrNick/github-tag-action@v1
-        id: tag
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          TAG_PREFIX: v
+  #     - name: Bump version and push tag
+  #       uses: anothrNick/github-tag-action@v1
+  #       id: tag
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #         TAG_PREFIX: v
 
-      - name: Create and schedule change
-        id: create-change
-        run: |
-          ./snow_change_manager.py create \
-            --short-description "$SHORT_DESCRIPTION" \
-            --standard-change $SNOW_STANDARD_CHANGE  \
-            | grep '=' \
-            > snow_variables.sh
+  #     - name: Create and schedule change
+  #       id: create-change
+  #       run: |
+  #         ./snow_change_manager.py create \
+  #           --short-description "$SHORT_DESCRIPTION" \
+  #           --standard-change $SNOW_STANDARD_CHANGE  \
+  #           | grep '=' \
+  #           > snow_variables.sh
 
-          echo Change created successfully and scheduled immediately
-          cat snow_variables.sh
+  #         echo Change created successfully and scheduled immediately
+  #         cat snow_variables.sh
 
-          source snow_variables.sh
-          echo "CHANGE_SYS_ID=$CHANGE_SYS_ID" >> $GITHUB_OUTPUT
+  #         source snow_variables.sh
+  #         echo "CHANGE_SYS_ID=$CHANGE_SYS_ID" >> $GITHUB_OUTPUT
 
-          WORKFLOW_RUN_LINK=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
-          ./snow_change_manager.py post-comment \
-            --sys-id $CHANGE_SYS_ID \
-            --comment "Commit SHA: ${{github.sha}}
-            Link to [code]<a href=\"$WORKFLOW_RUN_LINK\" target=\"_blank\">Github action workflow</a>[/code]
-            Triggered by ${{github.actor}}"
-        env:
-          SHORT_DESCRIPTION: "Release Manage breast screening version ${{steps.tag.outputs.tag}}"
-          SNOW_STANDARD_CHANGE: 92b653b2537a7610065e78e0a0490e5e
-          SNOW_USER: ${{ secrets.SNOW_USER }}
-          SNOW_PASSWORD: ${{ secrets.SNOW_PASSWORD }}
+  #         WORKFLOW_RUN_LINK=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
+  #         ./snow_change_manager.py post-comment \
+  #           --sys-id $CHANGE_SYS_ID \
+  #           --comment "Commit SHA: ${{github.sha}}
+  #           Link to [code]<a href=\"$WORKFLOW_RUN_LINK\" target=\"_blank\">Github action workflow</a>[/code]
+  #           Triggered by ${{github.actor}}"
+  #       env:
+  #         SHORT_DESCRIPTION: "Release Manage breast screening version ${{steps.tag.outputs.tag}}"
+  #         SNOW_STANDARD_CHANGE: 92b653b2537a7610065e78e0a0490e5e
+  #         SNOW_USER: ${{ secrets.SNOW_USER }}
+  #         SNOW_PASSWORD: ${{ secrets.SNOW_PASSWORD }}
 
-  deploy:
-    name: Deploy to production
-    runs-on: ubuntu-latest
-    needs: [create-snow-change]
-    env:
-      SNOW_URL: https://dev280175.service-now.com
-    outputs:
-      CHANGE_SYS_ID: ${{ needs.create-snow-change.outputs.CHANGE_SYS_ID }}
+  # deploy:
+  #   name: Deploy to production
+  #   runs-on: ubuntu-latest
+  #   needs: [create-snow-change]
+  #   env:
+  #     SNOW_URL: https://dev280175.service-now.com
+  #   outputs:
+  #     CHANGE_SYS_ID: ${{ needs.create-snow-change.outputs.CHANGE_SYS_ID }}
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v5
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v5
 
-      - name: Start change
-        run: |
-          ./snow_change_manager.py update --sys-id $CHANGE_SYS_ID --state Implement
+  #     - name: Start change
+  #       run: |
+  #         ./snow_change_manager.py update --sys-id $CHANGE_SYS_ID --state Implement
 
-          echo Change started successfully. Ready for deployment.
-        env:
-          CHANGE_SYS_ID: ${{ needs.create-snow-change.outputs.CHANGE_SYS_ID }}
-          SNOW_USER: ${{ secrets.SNOW_USER }}
-          SNOW_PASSWORD: ${{ secrets.SNOW_PASSWORD }}
+  #         echo Change started successfully. Ready for deployment.
+  #       env:
+  #         CHANGE_SYS_ID: ${{ needs.create-snow-change.outputs.CHANGE_SYS_ID }}
+  #         SNOW_USER: ${{ secrets.SNOW_USER }}
+  #         SNOW_PASSWORD: ${{ secrets.SNOW_PASSWORD }}
 
-      - name: Deploy software
-        id: deploy-software
-        run: |
-          echo Deploying software... | tee -a deployment.log
-          sleep 5
+  #     - name: Deploy software
+  #       id: deploy-software
+  #       run: |
+  #         echo Deploying software... | tee -a deployment.log
+  #         sleep 5
 
-          if [[ "${{ inputs.expected_result }}" = "fail" ]]; then
-            echo Error: Deployment has failed. | tee -a deployment.log
-            {
-              echo 'LOG<<EOF'
-              cat deployment.log
-              echo EOF
-            } >> "$GITHUB_OUTPUT"
-            exit 1
-          fi
+  #         if [[ "${{ inputs.expected_result }}" = "fail" ]]; then
+  #           echo Error: Deployment has failed. | tee -a deployment.log
+  #           {
+  #             echo 'LOG<<EOF'
+  #             cat deployment.log
+  #             echo EOF
+  #           } >> "$GITHUB_OUTPUT"
+  #           exit 1
+  #         fi
 
-          echo Deployed software successfully | tee -a deployment.log
-          {
-            echo 'LOG<<EOF'
-            cat deployment.log
-            echo EOF
-          } >> "$GITHUB_OUTPUT"
+  #         echo Deployed software successfully | tee -a deployment.log
+  #         {
+  #           echo 'LOG<<EOF'
+  #           cat deployment.log
+  #           echo EOF
+  #         } >> "$GITHUB_OUTPUT"
 
-      - name: Review change
-        if: always()
-        run: |
-          ./snow_change_manager.py update --sys-id $CHANGE_SYS_ID --state Review
+  #     - name: Review change
+  #       if: always()
+  #       run: |
+  #         ./snow_change_manager.py update --sys-id $CHANGE_SYS_ID --state Review
 
-          if [[ "${{ job.status }}" != "success" ]]; then
-            message="The deployment was unsuccessul"
-          else
-            message="The deployment was successul"
-          fi
+  #         if [[ "${{ job.status }}" != "success" ]]; then
+  #           message="The deployment was unsuccessul"
+  #         else
+  #           message="The deployment was successul"
+  #         fi
 
-          echo "$message"
+  #         echo "$message"
 
-          ./snow_change_manager.py post-comment \
-            --sys-id $CHANGE_SYS_ID \
-            --comment "$message
-            Deployment log:
-            ${{ steps.deploy-software.outputs.LOG}}"
-        env:
-          CHANGE_SYS_ID: ${{ needs.create-snow-change.outputs.CHANGE_SYS_ID }}
-          SNOW_USER: ${{ secrets.SNOW_USER }}
-          SNOW_PASSWORD: ${{ secrets.SNOW_PASSWORD }}
+  #         ./snow_change_manager.py post-comment \
+  #           --sys-id $CHANGE_SYS_ID \
+  #           --comment "$message
+  #           Deployment log:
+  #           ${{ steps.deploy-software.outputs.LOG}}"
+  #       env:
+  #         CHANGE_SYS_ID: ${{ needs.create-snow-change.outputs.CHANGE_SYS_ID }}
+  #         SNOW_USER: ${{ secrets.SNOW_USER }}
+  #         SNOW_PASSWORD: ${{ secrets.SNOW_PASSWORD }}
 
-      - name: Run smoke tests
-        run: |
-          echo Testing the deployment...
-          sleep 5
+  #     - name: Run smoke tests
+  #       run: |
+  #         echo Testing the deployment...
+  #         sleep 5
 
-  close-change:
-    name: Close ServiceNow change
-    if: always()
-    runs-on: ubuntu-latest
-    needs: [deploy]
-    env:
-      SNOW_URL: https://dev280175.service-now.com
+  # close-change:
+  #   name: Close ServiceNow change
+  #   if: always()
+  #   runs-on: ubuntu-latest
+  #   needs: [deploy]
+  #   env:
+  #     SNOW_URL: https://dev280175.service-now.com
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v5
-      - name: Close change
-        if: always()
-        run: |
-          if [[ "${{ needs.deploy.result }}" = "success" ]]; then
-            result=successful
-          else
-            result=unsuccessful
-          fi
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v5
+  #     - name: Close change
+  #       if: always()
+  #       run: |
+  #         if [[ "${{ needs.deploy.result }}" = "success" ]]; then
+  #           result=successful
+  #         else
+  #           result=unsuccessful
+  #         fi
 
-          ./snow_change_manager.py update --sys-id $CHANGE_SYS_ID --state Closed --result $result
+  #         ./snow_change_manager.py update --sys-id $CHANGE_SYS_ID --state Closed --result $result
 
-          echo Change closed with result: $result
-        env:
-          CHANGE_SYS_ID: ${{ needs.deploy.outputs.CHANGE_SYS_ID }}
-          SNOW_USER: ${{ secrets.SNOW_USER }}
-          SNOW_PASSWORD: ${{ secrets.SNOW_PASSWORD }}
+  #         echo Change closed with result: $result
+  #       env:
+  #         CHANGE_SYS_ID: ${{ needs.deploy.outputs.CHANGE_SYS_ID }}
+  #         SNOW_USER: ${{ secrets.SNOW_USER }}
+  #         SNOW_PASSWORD: ${{ secrets.SNOW_PASSWORD }}
